### ISSUE TITLE
Bad performance when navigate to another screen

### ISSUE THREAD

**Issue by doublelam** [callstack/react-native-fbads#238]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Ad Modules**

Native Ads

**Platforms**

iOS

**Versions**

- Android:
- iOS: 13
- react-native-fbads: 6.3.1
- react-native: 0.61.5

**Ads Environment**

- Facebook app installed: Y
- Happens in test (dev build + device is marked as a test device): Y
- Happens in production (release build + **not** a test device): Y
- Facebook review status: [approved]

**Current Behaviour**

I have added native ads on a screen, at this moment, it works well, but when I navigate to another screen the UI frame will be dropped to a low number,  and when I am using the instruments to profile it, it shows that the cpu usage reached to a higher number

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

![image](https://user-images.githubusercontent.com/12025501/72402119-1d4f3980-3789-11ea-9135-57cd1427953e.png)
![image](https://user-images.githubusercontent.com/12025501/72402333-ec233900-3789-11ea-80b0-5e441fb5d2a3.png)

**Comment by mrousavy** [comment]
I think there's a function that repeatedly checks if the Native Ad is on screen to ensure that you get paid for showing that ad. That function seems to be doing something wrong, since it spikes up your CPU usage making native ads unusable. Can a maintainer here please take a look at this? It's also time to upgrade to SDK 6 since the old one doesn't work at all anymore without warnings https://github.com/callstack/react-native-fbads/issues/257

**Comment by TMaszko** [comment]
Please check out v7 available now ! :) if it hasn't been fixed yet then please reopen it.
