### ISSUE TITLE
Outdated FBAudienceNetwork.framework in FacebookSDK-v4.3

### ISSUE THREAD

**Issue by RyszardRzepa** [callstack/react-native-fbads#90]
I am running on this error:
**Include of non-modular header inside framework module 'FBAudienceNetwork': '/Users/ryrz01/Downloads/solapp/ios/Pods/Headers/Public/FBAudienceNetwork/FBAudienceNetwork/FBAdSize.h'**

I am using FacebookSdk-ios-4.3, where FBAudienceNetwork.framework is not included.
Following Facebook docs, I added 4 files:
![screen shot 2018-02-01 at 15 03 26](https://user-images.githubusercontent.com/13038459/35682479-2619a2c6-0761-11e8-8fe9-836beefd6988.png)

Does anyone have the same issue?

**Comment by gesf** [comment]
Not this error specifically, but I was also having issues because of the missing _FBAudienceNetwork.framework_ file and couldn't find any information on why that file doesn't come along with the others and how could I do without it. I am using v4.30. At some point just decided to go to v.4.26, still the two _FBAudienceNetwork*.framework_ files, include them in my _~/Documents/FacebookSDK_ and ... voilà :)

**Comment by Im-Goutham** [comment]
Can you please give a link to get FBAudienceNetwork ?

**Comment by erandagan** [comment]
This newest version of this package uses the 4.99 SDK.
